name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza a cobrinha todo dia à meia-noite UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: LoPedrozo
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando cobrinha 🐍"
          add: "github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg"
          author_name: "GitHub Actions"
          author_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Usando o token correto
